<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="wjn" name="kuangjia_qiantai_test.liuyanTest" tests="6" failures="0" timestamp="12 Dec 2017 07:30:35 GMT" time="71.288" errors="1">
  <testcase name="testdianji" time="10.010" classname="kuangjia_qiantai_test.liuyanTest"/>
  <testcase name="testkejian" time="13.118" classname="kuangjia_qiantai_test.liuyanTest"/>
  <testcase name="testneirong" time="18.411" classname="kuangjia_qiantai_test.liuyanTest"/>
  <testcase name="testshuru" time="16.363" classname="kuangjia_qiantai_test.liuyanTest"/>
  <testcase name="testliuyan_sjqd" time="0.000" classname="kuangjia_qiantai_test.liuyanTest">
    <error type="java.lang.RuntimeException" message="Can&#039;t invoke method public java.lang.Object[][] dataprovider.NSDataProvider4.getData() on this instance of class kuangjia_qiantai_test.liuyanTest due to class mismatch">
      <![CDATA[java.lang.RuntimeException: Can't invoke method public java.lang.Object[][] dataprovider.NSDataProvider4.getData() on this instance of class kuangjia_qiantai_test.liuyanTest due to class mismatch
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </error>
  </testcase> <!-- testliuyan_sjqd -->
  <testcase name="testjieshou" time="13.386" classname="kuangjia_qiantai_test.liuyanTest"/>
</testsuite> <!-- kuangjia_qiantai_test.liuyanTest -->
